image: gitpod/workspace-dotnet
# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'
  - name: Restore & Build
    init: |
      cd src
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run server
    command: |
      dotnet run

  - name: Run ui
    command: |
      cd client-app
      npm start
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
  extensions:
    - muhammad-sammy.csharp